<?php
/**
 * jsconfig.phtml
 *
 * @category Magento_Module
 * @package  Hevelop_FacebookPixel
 * @author   Simone Marcato <simone@hevelop.com>
 * @license  http://opensource.org/licenses/agpl-3.0  GNU Affero General Public License v3 (AGPL-3.0)
 * @link     https://github.com/Hevelop/Facebookpixel
 */
?>
<script type="text/javascript">

    (function (w) {

        w.cookieAddToCart = '<?php echo Hevelop_FacebookPixel_Helper_Data::COOKIE_CART_ADD ?>';
        w.cookieRemoveFromCart = '<?php echo Hevelop_FacebookPixel_Helper_Data::COOKIE_CART_REMOVE ?>';
        w.cookieAddToWishlist = '<?php echo Hevelop_FacebookPixel_Helper_Data::COOKIE_WISHLIST_ADD ?>';
        w.cookieCustomerRegistered = '<?php echo Hevelop_FacebookPixel_Helper_Data::COOKIE_CUSTOMER_REGISTER ?>';

    })(window);

</script>