<script type="text/javascript">

    (function (w) {

        w.cookieAddToCart = '<?php echo Hevelop_FacebookPixel_Helper_Data::COOKIE_CART_ADD ?>';
        w.cookieRemoveFromCart = '<?php echo Hevelop_FacebookPixel_Helper_Data::COOKIE_CART_REMOVE ?>';
        w.cookieAddToWishlist = '<?php echo Hevelop_FacebookPixel_Helper_Data::COOKIE_WISHLIST_ADD ?>';
        w.cookieCustomerRegistered = '<?php echo Hevelop_FacebookPixel_Helper_Data::COOKIE_CUSTOMER_REGISTER ?>';

    })(window);

</script>